[workspace]
authors = ["philipreese <pbreese42@gmail.com>"]
channels = ["conda-forge"]
name = "budget-tracker"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"
